# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Vivado/MyProject/CPU_sim/CPU_sim.srcs/sources_1/ip/clk_divide/clk_divide.xci
# IP: The module: 'clk_divide' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/MyProject/CPU_sim/CPU_sim.srcs/sources_1/ip/clk_divide/clk_divide_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_divide'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Vivado/MyProject/CPU_sim/CPU_sim.srcs/sources_1/ip/clk_divide/clk_divide.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_divide'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Vivado/MyProject/CPU_sim/CPU_sim.srcs/sources_1/ip/clk_divide/clk_divide_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_divide'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Vivado/MyProject/CPU_sim/CPU_sim.srcs/sources_1/ip/clk_divide/clk_divide.xci
# IP: The module: 'clk_divide' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/MyProject/CPU_sim/CPU_sim.srcs/sources_1/ip/clk_divide/clk_divide_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_divide'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Vivado/MyProject/CPU_sim/CPU_sim.srcs/sources_1/ip/clk_divide/clk_divide.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_divide'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Vivado/MyProject/CPU_sim/CPU_sim.srcs/sources_1/ip/clk_divide/clk_divide_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_divide'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
