# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Vivado/MyProject/CPU_sim/CPU_sim.srcs/sources_1/ip/rom_cm/rom_cm.xci
# IP: The module: 'rom_cm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/MyProject/CPU_sim/CPU_sim.srcs/sources_1/ip/rom_cm/rom_cm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_cm'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/Vivado/MyProject/CPU_sim/CPU_sim.srcs/sources_1/ip/rom_cm/rom_cm.xci
# IP: The module: 'rom_cm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/MyProject/CPU_sim/CPU_sim.srcs/sources_1/ip/rom_cm/rom_cm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_cm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
