# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Vivado/MyProject/CPU_sim/Nexys4DDR_Master.xdc

# IP: ip/ram_mem/ram_mem.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ram_mem || ORIG_REF_NAME==ram_mem} -quiet] -quiet
